# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

pool:
    name: 'Default'
    demands:
        - agent.name -equals instance-20241203-145320

steps:

- task: Docker@2
  displayName: 'Login to Docker Registry'
  inputs:
    command: 'login'
    containerRegistry: 'docker'

- script: |
      docker buildx build -t romanbeggar/backend:latest .
  displayName: 'Docker Build'

- script: |
      docker push romanbeggar/backend:latest