# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

pool:
    name: 'Default'
    demands:
        - agent.name -equals instance-20241203-145320

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: 'romanbeggar/backend'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'