# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'Default'
      demands:
        - agent.name -equals instance-20241203-145320

    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker'
        repository: 'romanbeggar/backend'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: '.'
        buildArguments: |
          --build-arg BUILDKIT=1  # Включение BuildKit
        tags: $(tag)
