# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: "Default"
  demands: 
    - agent.name -equals instance-20250110-002118

steps:

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'myconnect'
    scannerMode: 'cli'
    configMode: 'manual'
    cliProjectKey: 'kubernetes_kubernetes_24c6e2eb-ad07-4115-8806-f9fa4128c635'
    cliSources: '.'

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    workingDirectory: './'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '2.6.1'
    spotBugsAnalysis: true
    spotBugsGradlePluginVersionChoice: 'specify'
    spotbugsGradlePluginVersion: '4.7.0'

- task: SonarQubeAnalyze@7
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'